#!/bin/bash
cd /home/a/projects/flang/.claude/worktrees/agent-a4daa59c6b3b8bbfc
export LC_ALL=C.UTF-8
V=".rab/vydelit.mjs"
node $V dictionary.flang   "Ключ связи"                  docs/zamer2/01-klyuch-svyazi.flang       "Замер2 01: Ключ связи"
node $V hashmap.flang      "Ключ звена"                  docs/zamer2/02-klyuch-zvena.flang        "Замер2 02: Ключ звена"
node $V hashmap.flang      "Вписать"                     docs/zamer2/03-vpisat.flang              "Замер2 03: Вписать"
node $V hashmap.flang      "Размер словаря"              docs/zamer2/04-razmer-slovarya.flang     "Замер2 04: Размер словаря"
node $V higher-order.flang "Противоположное"             docs/zamer2/05-protivopolozhnoe.flang    "Замер2 05: Противоположное"
node $V higher-order.flang "Приписать в начало"          docs/zamer2/06-pripisat-v-nachalo.flang  "Замер2 06: Приписать в начало"
node $V higher-order.flang "Вставить по"                 docs/zamer2/07-vstavit-po.flang          "Замер2 07: Вставить по"
node $V higher-order.flang "Максимум"                    docs/zamer2/08-maksimum.flang            "Замер2 08: Максимум"
node $V lists.flang        "Взять первые"                docs/zamer2/09-vzyat-pervye.flang        "Замер2 09: Взять первые"
node $V lists.flang        "Двоичный поиск"              docs/zamer2/10-dvoichnyj-poisk.flang     "Замер2 10: Двоичный поиск"
node $V lists.flang        "Уникальные"                  docs/zamer2/11-unikalnye.flang           "Замер2 11: Уникальные"
node $V logic.flang        "Следует"                     docs/zamer2/12-sleduet.flang             "Замер2 12: Следует"
node $V numbers.flang      "Чётное"                      docs/zamer2/13-chyotnoe.flang            "Замер2 13: Чётное"
node $V numtree.flang      "Дерево из чисел"             docs/zamer2/14-derevo-iz-chisel.flang    "Замер2 14: Дерево из чисел"
node $V optional.flang     "Первый элемент или запасное" docs/zamer2/15-pervyj-ili-zapasnoe.flang "Замер2 15: Первый элемент или запасное"
node $V result.flang       "Успешно"                     docs/zamer2/16-uspeshno.flang            "Замер2 16: Успешно"
node $V sets.flang         "Есть в множестве"            docs/zamer2/17-est-v-mnozhestve.flang    "Замер2 17: Есть в множестве"
node $V strings.flang      "Приписать строку в начало"   docs/zamer2/18-pripisat-stroku.flang     "Замер2 18: Приписать строку в начало"
node $V strings.flang      "Строчная буква"              docs/zamer2/19-strochnaya-bukva.flang    "Замер2 19: Строчная буква"
node $V strings.flang      "Обрезать пробелы"            docs/zamer2/20-obrezat-probely.flang     "Замер2 20: Обрезать пробелы"
